---
name: PR Check

on:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install packages
        run: pip3 install -r requirements.txt

      - name: Run pre-commit
        run: pre-commit run --all-files --show-diff-on-failure
